// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetSessionInfo() {
  return window['go']['main']['App']['GetSessionInfo']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function HandleClientLogin(arg1, arg2) {
  return window['go']['main']['App']['HandleClientLogin'](arg1, arg2);
}

export function HandlePCRegistration() {
  return window['go']['main']['App']['HandlePCRegistration']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}
