// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';
import {api} from '../models';

export function GetSessionInfo():Promise<session.SessionData>;

export function GetSystemInfo():Promise<Record<string, string>>;

export function HandleClientLogin(arg1:string,arg2:string):Promise<api.AuthResultDTO>;

export function HandlePCRegistration():Promise<api.PCRegistrationResultDTO>;

export function IsConnected():Promise<boolean>;

export function Logout():Promise<void>;
