// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptControlRequest(arg1) {
  return window['go']['main']['App']['AcceptControlRequest'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetAppStatus() {
  return window['go']['main']['App']['GetAppStatus']();
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetPCInfo() {
  return window['go']['main']['App']['GetPCInfo']();
}

export function GetRemoteControlStatus() {
  return window['go']['main']['App']['GetRemoteControlStatus']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function IsAuthenticated() {
  return window['go']['main']['App']['IsAuthenticated']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function RegisterPC() {
  return window['go']['main']['App']['RegisterPC']();
}

export function RejectControlRequest(arg1, arg2) {
  return window['go']['main']['App']['RejectControlRequest'](arg1, arg2);
}

export function SetRemoteControlSettings(arg1, arg2) {
  return window['go']['main']['App']['SetRemoteControlSettings'](arg1, arg2);
}

export function TestRemoteControlCapabilities() {
  return window['go']['main']['App']['TestRemoteControlCapabilities']();
}
