// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AcceptControlRequest(arg1:string):Promise<Record<string, any>>;

export function AddVideoFrame(arg1:Array<number>):Promise<void>;

export function Connect(arg1:string):Promise<Record<string, any>>;

export function Disconnect():Promise<Record<string, any>>;

export function GetActiveFileTransfers():Promise<Record<string, any>>;

export function GetAppStatus():Promise<Record<string, any>>;

export function GetConnectionStatus():Promise<Record<string, any>>;

export function GetFileTransferDirectory():Promise<Record<string, any>>;

export function GetPCInfo():Promise<Record<string, any>>;

export function GetRemoteControlStatus():Promise<Record<string, any>>;

export function GetSystemInfo():Promise<Record<string, any>>;

export function GetVideoRecordingState():Promise<main.VideoRecordingState>;

export function GetVideoRecordingStatus():Promise<Record<string, any>>;

export function IsAuthenticated():Promise<boolean>;

export function IsVideoRecording():Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<Record<string, any>>;

export function Logout():Promise<Record<string, any>>;

export function RegisterPC():Promise<Record<string, any>>;

export function RejectControlRequest(arg1:string,arg2:string):Promise<Record<string, any>>;

export function SetRemoteControlSettings(arg1:number,arg2:number):Promise<Record<string, any>>;

export function StartVideoRecording(arg1:string):Promise<void>;

export function StopVideoRecording():Promise<void>;

export function TestRemoteControlCapabilities():Promise<Record<string, any>>;
